# Nodes module

from .base64_nodes import NODE_CLASS_MAPPINGS as BASE64_NODE_MAPPINGS
from .base64_nodes import NODE_DISPLAY_NAME_MAPPINGS as BASE64_DISPLAY_NAME_MAPPINGS
from .image_size_nodes import NODE_CLASS_MAPPINGS as IMAGE_SIZE_NODE_MAPPINGS
from .image_size_nodes import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_SIZE_DISPLAY_NAME_MAPPINGS

# 合并节点映射
NODE_CLASS_MAPPINGS = {**BASE64_NODE_MAPPINGS, **IMAGE_SIZE_NODE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BASE64_DISPLAY_NAME_MAPPINGS, **IMAGE_SIZE_DISPLAY_NAME_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
